name: GitHub-Profile-3D-Contrib

on: push
  # schedule: # 03:00 JST == 18:00 UTC
  #   - cron: "30 3 * * *"
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: ${{ github.repository_count }}
      - name: Commit & Push
        run: |
          git config user.name bhaktibhatt
          git config user.email bhaktinirbhaybhatt@gmail.com
          git add -A .
          git commit -m "generated"
          git push
